---
name: "Setup JDK 17"
description: "Setup JDK 17"
runs:
  using: "composite"
  steps:
    - name: Setup JDK 17
      uses: actions/setup-java@v3.11.0
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'